# ˝æ›ø‚≈‰÷√
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db3?autoReconnect=true&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    jcache:
      config: classpath:ehcache.xml


#mybatis≈‰÷√
mybatis:
  type-aliases-package: com.feng.ehcache.model
  #mapper-locations: classpath:mapper/*.xml;
